export const paths = {
  companyPath: "/company-manager/company/",
  companyDeletePath: "/company-manager/company-delete/",
  companyProductPath: "/company-manager/company/save/",
  userPath: "/company-manager/user/",
  clientPath: "/company-manager/client/",
  companyProductPlanPath: "/marketplace/company-product-plan/",
  omniBlockPath: "/marketplace/ommi/block",
  companyListPath: "/company-manager/company-list/",
  userSavePath: "/company-manager/user/save/",

  reportConversationPath: "/marketplace/company-conversation/reports",
  reportAttendencyPath: "/marketplace/company-attendency/reports",
  deleteProcutPlanPath: "/marketplace/delete",
  deleteLogicProductPath: "marketplace/product/delete-logic",

  omiePath: "/company-manager/integration-omie/getAll",
  pagiinationCountPath: "/company-manager/company-page",
  userByCompanyPath: "/company-manager/user/list",
  planSavePath: "/marketplace/plan/save",
  planByProductPath: "/marketplace/plan-by-product",
  companyProduct: "/marketplace/company-product/",
  commpanyProductPlanList: "/marketplace/company-product-plan/list",
  companyProductConfig: "/marketplace/company-product-config/",
  companyProductConfigListPath: "/marketplace/company-product-config/list/",
  profilePath: "/company-manager/profile/",
  profileSavePath: "/company-manager/profile/save/",
  profileUpdatePath: "/company-manager/profile/update/",
  actionPath: "/company-manager/action/",
  functionalityPath: "/company-manager/functionality/",
  functionalityByProductPath: "/company-manager/functionality/custom/",
  functionalityActionPath: "/company-manager/functionality-action/",
  profileFunctionalityActionPath:
    "/company-manager/profile-functionality-action/",
  rolePath: "/company-manager/role/",
  planPath: "/marketplace/plan/",
  planDetailPath: "/marketplace/plan-detail/",
  productPath: "/marketplace/product/",
  productSavePath: "/marketplace/product/",
  maintenanceSavePath: "/marketplace/manutention/save/",
  maintenancePath: "/marketplace/manutention/",
  maintenanceUpdatePath: "/marketplace/manutention/update/",
  maintenanceAuthorizationPath: "/marketplace/manutention-authorization/",

  pathChangePassword: "/auth/change-password/",
  loginPath: "/auth/login/",
  logoutPath: "/auth/logout/",
  forgotPasswordPath: "/auth/forgot-password/",

  brokerPath: "/channel-manager/broker/",
  channelPath: "/channel-manager/channel/",

  configPath: "/marketplace/product-config/",
  whatsappConfigPath: "/marketplace/whatsapp-config/",

  templatePath: "/notification/template/",
  templateCreatePath: "/notification/template-create/",
  templateTypePath: "/notification/template-type/",
  variablePath: "/notification/variable/",
  validationPath: "/auth/validation/",

  attachmentPath: "/notification/attachment-template/",

  massivePath: "/massive/massive/",
  massivePathSave: "/massive/massive/save/",
  productGetOnePath: "/marketplace/product/by-scope",

  //auditPath: "/audit/audit/",
  //auditPathSave: "/audit/audit/save/",
  //productGetOnePath: "/marketplace/product/by-scope",
};
